//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ICAIntegration.webRefICA {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PersonProfileEnquiryHttpBinding", Namespace="http://id.gov.ae/ws/enquiry/profile")]
    public partial class PersonProfileEnquiryHttpService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getPersonProfilePhotoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPersonProfileInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPersonStatsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PersonProfileEnquiryHttpService() {
            this.Url = global::ICAIntegration.Properties.Settings.Default.ICAIntegration_webRefICA_PersonProfileEnquiryHttpService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getPersonProfilePhotoCompletedEventHandler getPersonProfilePhotoCompleted;
        
        /// <remarks/>
        public event getPersonProfileInfoCompletedEventHandler getPersonProfileInfoCompleted;
        
        /// <remarks/>
        public event getPersonStatsCompletedEventHandler getPersonStatsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://id.gov.ae/ws/enquiry/profile/getPersonPhoto", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getPersonProfilePhotoResponse", Namespace="http://id.gov.ae/ws/enquiry/profile")]
        public GetPersonProfilePhotoResponseType getPersonProfilePhoto([System.Xml.Serialization.XmlElementAttribute("getPersonProfilePhoto", Namespace="http://id.gov.ae/ws/enquiry/profile")] GetPersonProfilePhotoRequestType getPersonProfilePhoto1) {
            object[] results = this.Invoke("getPersonProfilePhoto", new object[] {
                        getPersonProfilePhoto1});
            return ((GetPersonProfilePhotoResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void getPersonProfilePhotoAsync(GetPersonProfilePhotoRequestType getPersonProfilePhoto1) {
            this.getPersonProfilePhotoAsync(getPersonProfilePhoto1, null);
        }
        
        /// <remarks/>
        public void getPersonProfilePhotoAsync(GetPersonProfilePhotoRequestType getPersonProfilePhoto1, object userState) {
            if ((this.getPersonProfilePhotoOperationCompleted == null)) {
                this.getPersonProfilePhotoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPersonProfilePhotoOperationCompleted);
            }
            this.InvokeAsync("getPersonProfilePhoto", new object[] {
                        getPersonProfilePhoto1}, this.getPersonProfilePhotoOperationCompleted, userState);
        }
        
        private void OngetPersonProfilePhotoOperationCompleted(object arg) {
            if ((this.getPersonProfilePhotoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPersonProfilePhotoCompleted(this, new getPersonProfilePhotoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://id.gov.ae/ws/enquiry/profile/getPersonInfo", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getPersonProfileInfoResponse", Namespace="http://id.gov.ae/ws/enquiry/profile")]
        public GetPersonProfileInfoResponseType getPersonProfileInfo([System.Xml.Serialization.XmlElementAttribute("getPersonProfileInfo", Namespace="http://id.gov.ae/ws/enquiry/profile")] GetPersonProfileInfoRequestType getPersonProfileInfo1) {
            object[] results = this.Invoke("getPersonProfileInfo", new object[] {
                        getPersonProfileInfo1});
            return ((GetPersonProfileInfoResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void getPersonProfileInfoAsync(GetPersonProfileInfoRequestType getPersonProfileInfo1) {
            this.getPersonProfileInfoAsync(getPersonProfileInfo1, null);
        }
        
        /// <remarks/>
        public void getPersonProfileInfoAsync(GetPersonProfileInfoRequestType getPersonProfileInfo1, object userState) {
            if ((this.getPersonProfileInfoOperationCompleted == null)) {
                this.getPersonProfileInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPersonProfileInfoOperationCompleted);
            }
            this.InvokeAsync("getPersonProfileInfo", new object[] {
                        getPersonProfileInfo1}, this.getPersonProfileInfoOperationCompleted, userState);
        }
        
        private void OngetPersonProfileInfoOperationCompleted(object arg) {
            if ((this.getPersonProfileInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPersonProfileInfoCompleted(this, new getPersonProfileInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://id.gov.ae/ws/enquiry/profile/getPersonStats", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getPersonStatsResponse", Namespace="http://id.gov.ae/ws/enquiry/profile")]
        public GetPersonStatsResponseType getPersonStats([System.Xml.Serialization.XmlElementAttribute("getPersonStats", Namespace="http://id.gov.ae/ws/enquiry/profile")] GetPersonStatsRequestType getPersonStats1) {
            object[] results = this.Invoke("getPersonStats", new object[] {
                        getPersonStats1});
            return ((GetPersonStatsResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void getPersonStatsAsync(GetPersonStatsRequestType getPersonStats1) {
            this.getPersonStatsAsync(getPersonStats1, null);
        }
        
        /// <remarks/>
        public void getPersonStatsAsync(GetPersonStatsRequestType getPersonStats1, object userState) {
            if ((this.getPersonStatsOperationCompleted == null)) {
                this.getPersonStatsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPersonStatsOperationCompleted);
            }
            this.InvokeAsync("getPersonStats", new object[] {
                        getPersonStats1}, this.getPersonStatsOperationCompleted, userState);
        }
        
        private void OngetPersonStatsOperationCompleted(object arg) {
            if ((this.getPersonStatsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPersonStatsCompleted(this, new getPersonStatsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.gov.ae/schema/enquiry/profile")]
    public partial class GetPersonProfilePhotoRequestType {
        
        private HeaderType headerField;
        
        private GetPersonProfilePhotoRequestBodyType bodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://id.gov.ae/schema/commontypes")]
        public HeaderType Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        public GetPersonProfilePhotoRequestBodyType Body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.gov.ae/schema/commontypes")]
    public partial class HeaderType {
        
        private string serviceNameField;
        
        private string sourceChannelField;
        
        private string serviceVersionField;
        
        private string serviceLanguageField;
        
        private string userNameField;
        
        private string passwordField;
        
        private byte[] hashField;
        
        /// <remarks/>
        public string serviceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
            }
        }
        
        /// <remarks/>
        public string sourceChannel {
            get {
                return this.sourceChannelField;
            }
            set {
                this.sourceChannelField = value;
            }
        }
        
        /// <remarks/>
        public string serviceVersion {
            get {
                return this.serviceVersionField;
            }
            set {
                this.serviceVersionField = value;
            }
        }
        
        /// <remarks/>
        public string serviceLanguage {
            get {
                return this.serviceLanguageField;
            }
            set {
                this.serviceLanguageField = value;
            }
        }
        
        /// <remarks/>
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] hash {
            get {
                return this.hashField;
            }
            set {
                this.hashField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.gov.ae/schema/enquiry/profile")]
    public partial class GetPersonStatsResponseBodyType {
        
        private string transactionRefNoField;
        
        private int resultCodeField;
        
        private bool resultCodeFieldSpecified;
        
        private string responseCodeField;
        
        private string responseDescriptionField;
        
        private decimal pNoOfSponsoredField;
        
        private bool pNoOfSponsoredFieldSpecified;
        
        private decimal pNoOfRelatedEstablishmentField;
        
        private bool pNoOfRelatedEstablishmentFieldSpecified;
        
        private decimal pNoVisaRequestsField;
        
        private bool pNoVisaRequestsFieldSpecified;
        
        private decimal pNoResidenceRequestsField;
        
        private bool pNoResidenceRequestsFieldSpecified;
        
        private decimal pNoActiveVisasField;
        
        private bool pNoActiveVisasFieldSpecified;
        
        private decimal pNoActiveResidenciesField;
        
        private bool pNoActiveResidenciesFieldSpecified;
        
        private decimal pNoExpiredResidenciesField;
        
        private bool pNoExpiredResidenciesFieldSpecified;
        
        private System.DateTime pLastEntryDateField;
        
        private bool pLastEntryDateFieldSpecified;
        
        private System.DateTime pLastExitDateField;
        
        private bool pLastExitDateFieldSpecified;
        
        private System.DateTime timestampField;
        
        /// <remarks/>
        public string transactionRefNo {
            get {
                return this.transactionRefNoField;
            }
            set {
                this.transactionRefNoField = value;
            }
        }
        
        /// <remarks/>
        public int resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resultCodeSpecified {
            get {
                return this.resultCodeFieldSpecified;
            }
            set {
                this.resultCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string responseDescription {
            get {
                return this.responseDescriptionField;
            }
            set {
                this.responseDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public decimal pNoOfSponsored {
            get {
                return this.pNoOfSponsoredField;
            }
            set {
                this.pNoOfSponsoredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pNoOfSponsoredSpecified {
            get {
                return this.pNoOfSponsoredFieldSpecified;
            }
            set {
                this.pNoOfSponsoredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal pNoOfRelatedEstablishment {
            get {
                return this.pNoOfRelatedEstablishmentField;
            }
            set {
                this.pNoOfRelatedEstablishmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pNoOfRelatedEstablishmentSpecified {
            get {
                return this.pNoOfRelatedEstablishmentFieldSpecified;
            }
            set {
                this.pNoOfRelatedEstablishmentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal pNoVisaRequests {
            get {
                return this.pNoVisaRequestsField;
            }
            set {
                this.pNoVisaRequestsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pNoVisaRequestsSpecified {
            get {
                return this.pNoVisaRequestsFieldSpecified;
            }
            set {
                this.pNoVisaRequestsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal pNoResidenceRequests {
            get {
                return this.pNoResidenceRequestsField;
            }
            set {
                this.pNoResidenceRequestsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pNoResidenceRequestsSpecified {
            get {
                return this.pNoResidenceRequestsFieldSpecified;
            }
            set {
                this.pNoResidenceRequestsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal pNoActiveVisas {
            get {
                return this.pNoActiveVisasField;
            }
            set {
                this.pNoActiveVisasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pNoActiveVisasSpecified {
            get {
                return this.pNoActiveVisasFieldSpecified;
            }
            set {
                this.pNoActiveVisasFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal pNoActiveResidencies {
            get {
                return this.pNoActiveResidenciesField;
            }
            set {
                this.pNoActiveResidenciesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pNoActiveResidenciesSpecified {
            get {
                return this.pNoActiveResidenciesFieldSpecified;
            }
            set {
                this.pNoActiveResidenciesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal pNoExpiredResidencies {
            get {
                return this.pNoExpiredResidenciesField;
            }
            set {
                this.pNoExpiredResidenciesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pNoExpiredResidenciesSpecified {
            get {
                return this.pNoExpiredResidenciesFieldSpecified;
            }
            set {
                this.pNoExpiredResidenciesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime pLastEntryDate {
            get {
                return this.pLastEntryDateField;
            }
            set {
                this.pLastEntryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pLastEntryDateSpecified {
            get {
                return this.pLastEntryDateFieldSpecified;
            }
            set {
                this.pLastEntryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime pLastExitDate {
            get {
                return this.pLastExitDateField;
            }
            set {
                this.pLastExitDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pLastExitDateSpecified {
            get {
                return this.pLastExitDateFieldSpecified;
            }
            set {
                this.pLastExitDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.gov.ae/schema/enquiry/profile")]
    public partial class GetPersonStatsResponseType {
        
        private HeaderType headerField;
        
        private GetPersonStatsResponseBodyType bodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://id.gov.ae/schema/commontypes")]
        public HeaderType Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        public GetPersonStatsResponseBodyType Body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.gov.ae/schema/enquiry/profile")]
    public partial class GetPersonStatsRequestBodyType {
        
        private string transactionRefNoField;
        
        private string unifiedNoField;
        
        private string idnField;
        
        private System.DateTime timestampField;
        
        /// <remarks/>
        public string transactionRefNo {
            get {
                return this.transactionRefNoField;
            }
            set {
                this.transactionRefNoField = value;
            }
        }
        
        /// <remarks/>
        public string unifiedNo {
            get {
                return this.unifiedNoField;
            }
            set {
                this.unifiedNoField = value;
            }
        }
        
        /// <remarks/>
        public string idn {
            get {
                return this.idnField;
            }
            set {
                this.idnField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.gov.ae/schema/enquiry/profile")]
    public partial class GetPersonStatsRequestType {
        
        private HeaderType headerField;
        
        private GetPersonStatsRequestBodyType bodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://id.gov.ae/schema/commontypes")]
        public HeaderType Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        public GetPersonStatsRequestBodyType Body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.gov.ae/schema/enquiry/profile")]
    public partial class lastTravelEntryDetailsType {
        
        private string flightNoField;
        
        private CodeType arrivalAirportField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string flightNo {
            get {
                return this.flightNoField;
            }
            set {
                this.flightNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CodeType arrivalAirport {
            get {
                return this.arrivalAirportField;
            }
            set {
                this.arrivalAirportField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.gov.ae/schema/enquiry/profile")]
    public partial class CodeType {
        
        private string nameField;
        
        private string arabic_descField;
        
        private string english_descField;
        
        private int valueField;
        
        public CodeType() {
            this.nameField = "lookup";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string arabic_desc {
            get {
                return this.arabic_descField;
            }
            set {
                this.arabic_descField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string english_desc {
            get {
                return this.english_descField;
            }
            set {
                this.english_descField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public int Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.gov.ae/schema/enquiry/profile")]
    public partial class activeHomeDocumentType {
        
        private CodeType documentTypeField;
        
        private CodeType idIssueNationalityField;
        
        private CodeType idNationalityField;
        
        private string documentNoField;
        
        private System.DateTime issueDateField;
        
        private bool issueDateFieldSpecified;
        
        private System.DateTime expiryDateField;
        
        private bool expiryDateFieldSpecified;
        
        /// <remarks/>
        public CodeType documentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
            }
        }
        
        /// <remarks/>
        public CodeType idIssueNationality {
            get {
                return this.idIssueNationalityField;
            }
            set {
                this.idIssueNationalityField = value;
            }
        }
        
        /// <remarks/>
        public CodeType idNationality {
            get {
                return this.idNationalityField;
            }
            set {
                this.idNationalityField = value;
            }
        }
        
        /// <remarks/>
        public string documentNo {
            get {
                return this.documentNoField;
            }
            set {
                this.documentNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime issueDate {
            get {
                return this.issueDateField;
            }
            set {
                this.issueDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool issueDateSpecified {
            get {
                return this.issueDateFieldSpecified;
            }
            set {
                this.issueDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime expiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expiryDateSpecified {
            get {
                return this.expiryDateFieldSpecified;
            }
            set {
                this.expiryDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.gov.ae/schema/enquiry/profile")]
    public partial class activePassportType {
        
        private CodeType passportTypeField;
        
        private CodeType passportIssueNationalityField;
        
        private CodeType passportNationalityField;
        
        private string passportNoField;
        
        private System.DateTime issueDateField;
        
        private bool issueDateFieldSpecified;
        
        private System.DateTime expiryDateField;
        
        private bool expiryDateFieldSpecified;
        
        /// <remarks/>
        public CodeType passportType {
            get {
                return this.passportTypeField;
            }
            set {
                this.passportTypeField = value;
            }
        }
        
        /// <remarks/>
        public CodeType passportIssueNationality {
            get {
                return this.passportIssueNationalityField;
            }
            set {
                this.passportIssueNationalityField = value;
            }
        }
        
        /// <remarks/>
        public CodeType passportNationality {
            get {
                return this.passportNationalityField;
            }
            set {
                this.passportNationalityField = value;
            }
        }
        
        /// <remarks/>
        public string passportNo {
            get {
                return this.passportNoField;
            }
            set {
                this.passportNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime issueDate {
            get {
                return this.issueDateField;
            }
            set {
                this.issueDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool issueDateSpecified {
            get {
                return this.issueDateFieldSpecified;
            }
            set {
                this.issueDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime expiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expiryDateSpecified {
            get {
                return this.expiryDateFieldSpecified;
            }
            set {
                this.expiryDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.gov.ae/schema/enquiry/profile")]
    public partial class ProfileInfoType {
        
        private long unifiedNoField;
        
        private bool unifiedNoFieldSpecified;
        
        private long idnField;
        
        private bool idnFieldSpecified;
        
        private string nameArabicField;
        
        private string nameEnglishField;
        
        private CodeType nationalityField;
        
        private System.DateTime birthDateField;
        
        private bool birthDateFieldSpecified;
        
        private string familyNameArField;
        
        private string familyNameEnField;
        
        private CodeType genderField;
        
        private CodeType religionField;
        
        private CodeType maritalStatusField;
        
        private activePassportType activePassportField;
        
        private activeHomeDocumentType activeHomeDocumentField;
        
        private CodeType residenceCountryField;
        
        private string emailField;
        
        private string mobileNoField;
        
        private string nationalIdField;
        
        private string nationalIdCardNoField;
        
        private System.DateTime nationalIdCardExpiryDateField;
        
        private bool nationalIdCardExpiryDateFieldSpecified;
        
        private string preferredLangField;
        
        private lastTravelEntryDetailsType lastTravelEntryDetailsField;
        
        private ProfileDocumentType[] profileDocumentField;
        
        /// <remarks/>
        public long unifiedNo {
            get {
                return this.unifiedNoField;
            }
            set {
                this.unifiedNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unifiedNoSpecified {
            get {
                return this.unifiedNoFieldSpecified;
            }
            set {
                this.unifiedNoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long idn {
            get {
                return this.idnField;
            }
            set {
                this.idnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idnSpecified {
            get {
                return this.idnFieldSpecified;
            }
            set {
                this.idnFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string nameArabic {
            get {
                return this.nameArabicField;
            }
            set {
                this.nameArabicField = value;
            }
        }
        
        /// <remarks/>
        public string nameEnglish {
            get {
                return this.nameEnglishField;
            }
            set {
                this.nameEnglishField = value;
            }
        }
        
        /// <remarks/>
        public CodeType nationality {
            get {
                return this.nationalityField;
            }
            set {
                this.nationalityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime birthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool birthDateSpecified {
            get {
                return this.birthDateFieldSpecified;
            }
            set {
                this.birthDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string familyNameAr {
            get {
                return this.familyNameArField;
            }
            set {
                this.familyNameArField = value;
            }
        }
        
        /// <remarks/>
        public string familyNameEn {
            get {
                return this.familyNameEnField;
            }
            set {
                this.familyNameEnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CodeType gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CodeType religion {
            get {
                return this.religionField;
            }
            set {
                this.religionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CodeType maritalStatus {
            get {
                return this.maritalStatusField;
            }
            set {
                this.maritalStatusField = value;
            }
        }
        
        /// <remarks/>
        public activePassportType activePassport {
            get {
                return this.activePassportField;
            }
            set {
                this.activePassportField = value;
            }
        }
        
        /// <remarks/>
        public activeHomeDocumentType activeHomeDocument {
            get {
                return this.activeHomeDocumentField;
            }
            set {
                this.activeHomeDocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CodeType residenceCountry {
            get {
                return this.residenceCountryField;
            }
            set {
                this.residenceCountryField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string mobileNo {
            get {
                return this.mobileNoField;
            }
            set {
                this.mobileNoField = value;
            }
        }
        
        /// <remarks/>
        public string nationalId {
            get {
                return this.nationalIdField;
            }
            set {
                this.nationalIdField = value;
            }
        }
        
        /// <remarks/>
        public string nationalIdCardNo {
            get {
                return this.nationalIdCardNoField;
            }
            set {
                this.nationalIdCardNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime nationalIdCardExpiryDate {
            get {
                return this.nationalIdCardExpiryDateField;
            }
            set {
                this.nationalIdCardExpiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nationalIdCardExpiryDateSpecified {
            get {
                return this.nationalIdCardExpiryDateFieldSpecified;
            }
            set {
                this.nationalIdCardExpiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string preferredLang {
            get {
                return this.preferredLangField;
            }
            set {
                this.preferredLangField = value;
            }
        }
        
        /// <remarks/>
        public lastTravelEntryDetailsType lastTravelEntryDetails {
            get {
                return this.lastTravelEntryDetailsField;
            }
            set {
                this.lastTravelEntryDetailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("profileDocument")]
        public ProfileDocumentType[] profileDocument {
            get {
                return this.profileDocumentField;
            }
            set {
                this.profileDocumentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.gov.ae/schema/enquiry/profile")]
    public partial class ProfileDocumentType {
        
        private ProfileDocumentCodeType binaryDocumentTypeField;
        
        private bool binaryDocumentTypeFieldSpecified;
        
        private byte[] binaryDocumentField;
        
        /// <remarks/>
        public ProfileDocumentCodeType binaryDocumentType {
            get {
                return this.binaryDocumentTypeField;
            }
            set {
                this.binaryDocumentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool binaryDocumentTypeSpecified {
            get {
                return this.binaryDocumentTypeFieldSpecified;
            }
            set {
                this.binaryDocumentTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] binaryDocument {
            get {
                return this.binaryDocumentField;
            }
            set {
                this.binaryDocumentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.gov.ae/schema/enquiry/profile")]
    public enum ProfileDocumentCodeType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.gov.ae/schema/enquiry/profile")]
    public partial class GetPersonProfileInfoResponseBodyType {
        
        private string transactionRefNoField;
        
        private int resultCodeField;
        
        private bool resultCodeFieldSpecified;
        
        private string responseCodeField;
        
        private string responseDescriptionField;
        
        private ProfileInfoType profileInfoField;
        
        private System.DateTime timestampField;
        
        /// <remarks/>
        public string transactionRefNo {
            get {
                return this.transactionRefNoField;
            }
            set {
                this.transactionRefNoField = value;
            }
        }
        
        /// <remarks/>
        public int resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resultCodeSpecified {
            get {
                return this.resultCodeFieldSpecified;
            }
            set {
                this.resultCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string responseDescription {
            get {
                return this.responseDescriptionField;
            }
            set {
                this.responseDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public ProfileInfoType profileInfo {
            get {
                return this.profileInfoField;
            }
            set {
                this.profileInfoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.gov.ae/schema/enquiry/profile")]
    public partial class GetPersonProfileInfoResponseType {
        
        private HeaderType headerField;
        
        private GetPersonProfileInfoResponseBodyType bodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://id.gov.ae/schema/commontypes")]
        public HeaderType Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        public GetPersonProfileInfoResponseBodyType Body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.gov.ae/schema/enquiry/profile")]
    public partial class GetPersonProfileInfoRequestBodyType {
        
        private string transactionRefNoField;
        
        private string unifiedNoField;
        
        private string idnField;
        
        private string passportNoField;
        
        private string nationalityCodeField;
        
        private System.DateTime timestampField;
        
        /// <remarks/>
        public string transactionRefNo {
            get {
                return this.transactionRefNoField;
            }
            set {
                this.transactionRefNoField = value;
            }
        }
        
        /// <remarks/>
        public string unifiedNo {
            get {
                return this.unifiedNoField;
            }
            set {
                this.unifiedNoField = value;
            }
        }
        
        /// <remarks/>
        public string idn {
            get {
                return this.idnField;
            }
            set {
                this.idnField = value;
            }
        }
        
        /// <remarks/>
        public string passportNo {
            get {
                return this.passportNoField;
            }
            set {
                this.passportNoField = value;
            }
        }
        
        /// <remarks/>
        public string nationalityCode {
            get {
                return this.nationalityCodeField;
            }
            set {
                this.nationalityCodeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.gov.ae/schema/enquiry/profile")]
    public partial class GetPersonProfileInfoRequestType {
        
        private HeaderType headerField;
        
        private GetPersonProfileInfoRequestBodyType bodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://id.gov.ae/schema/commontypes")]
        public HeaderType Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        public GetPersonProfileInfoRequestBodyType Body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.gov.ae/schema/enquiry/profile")]
    public partial class ProfileDocumentsType {
        
        private string unifiedNoField;
        
        private string idnField;
        
        private ProfileDocumentType[] profileDocumentField;
        
        /// <remarks/>
        public string unifiedNo {
            get {
                return this.unifiedNoField;
            }
            set {
                this.unifiedNoField = value;
            }
        }
        
        /// <remarks/>
        public string idn {
            get {
                return this.idnField;
            }
            set {
                this.idnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("profileDocument")]
        public ProfileDocumentType[] profileDocument {
            get {
                return this.profileDocumentField;
            }
            set {
                this.profileDocumentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.gov.ae/schema/enquiry/profile")]
    public partial class GetPersonProfilePhotoResponseBodyType {
        
        private string transactionRefNoField;
        
        private int resultCodeField;
        
        private bool resultCodeFieldSpecified;
        
        private string responseCodeField;
        
        private string responseDescriptionField;
        
        private ProfileDocumentsType profilePhotoField;
        
        private System.DateTime timestampField;
        
        /// <remarks/>
        public string transactionRefNo {
            get {
                return this.transactionRefNoField;
            }
            set {
                this.transactionRefNoField = value;
            }
        }
        
        /// <remarks/>
        public int resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resultCodeSpecified {
            get {
                return this.resultCodeFieldSpecified;
            }
            set {
                this.resultCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string responseDescription {
            get {
                return this.responseDescriptionField;
            }
            set {
                this.responseDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public ProfileDocumentsType profilePhoto {
            get {
                return this.profilePhotoField;
            }
            set {
                this.profilePhotoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.gov.ae/schema/enquiry/profile")]
    public partial class GetPersonProfilePhotoResponseType {
        
        private HeaderType headerField;
        
        private GetPersonProfilePhotoResponseBodyType bodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://id.gov.ae/schema/commontypes")]
        public HeaderType Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        public GetPersonProfilePhotoResponseBodyType Body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.gov.ae/schema/enquiry/profile")]
    public partial class GetPersonProfilePhotoRequestBodyType {
        
        private string transactionRefNoField;
        
        private string unifiedNoField;
        
        private string idnField;
        
        private System.DateTime timestampField;
        
        /// <remarks/>
        public string transactionRefNo {
            get {
                return this.transactionRefNoField;
            }
            set {
                this.transactionRefNoField = value;
            }
        }
        
        /// <remarks/>
        public string unifiedNo {
            get {
                return this.unifiedNoField;
            }
            set {
                this.unifiedNoField = value;
            }
        }
        
        /// <remarks/>
        public string idn {
            get {
                return this.idnField;
            }
            set {
                this.idnField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getPersonProfilePhotoCompletedEventHandler(object sender, getPersonProfilePhotoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPersonProfilePhotoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPersonProfilePhotoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetPersonProfilePhotoResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetPersonProfilePhotoResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getPersonProfileInfoCompletedEventHandler(object sender, getPersonProfileInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPersonProfileInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPersonProfileInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetPersonProfileInfoResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetPersonProfileInfoResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getPersonStatsCompletedEventHandler(object sender, getPersonStatsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPersonStatsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPersonStatsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetPersonStatsResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetPersonStatsResponseType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591